### ISSUE TITLE
After combining lcov initial tracefile with another trace file we loose branch coverage data

### ISSUE THREAD

**Issue by ysmaoui** [linux-test-project/lcov#39]
Hi,

so I know that lcov -c --initial does not support branch coverage. But is there a way to not loose the branch coverage data if we combine the initial tracefile with a tracefile containing branch coverage?

Thanks.

**Comment by oberpar** [comment]
It appears that lcov incorrectly reports "no branch coverage" when combining a file without branch coverage data with a file that contains branch coverage data. It seems that the bug only affects the output of the combine operation, while the resulting file correctly contains the combined data. I've pushed commit 94eac0ee870e58630d8052dca1181b0cf802525f to fix this display problem.

Could you check if this fixes your problem?

**Comment by ysmaoui** [comment]
Hi,

using 
` lcov: LCOV version 1.13-15-g94eac0e ` 
I still get no branch data after adding trace files together:
```
lcov --add-tracefile lcov_init.info --add-tracefile lcov_after_test_execution.info --output-file lcov_experiment_withFix.info
Combining tracefiles.
Reading tracefile lcov_init.info
Reading tracefile lcov_after_test_execution.info
lcov: WARNING: negative counts found in tracefile lcov_after_test_execution.info
Writing data to lcov_experiment_withFix.info
Summary coverage rate:
  lines......: xx.x% (xx of xx lines)
  functions..: xx.x% (xx of xx functions)
  branches...: no data found
```

**Comment by ysmaoui** [comment]
Hi,

I found my mistake: I didn't add the --rc lcov_branch_coverage=1 to the lcov --add-tracefile operation..

even without the fix (so with the official lcov 1.13) I get branch coverage data.

sorry for the confusion.
